#!/bin/bash
#########################################################################
# File Name: ipgw_new.sh
# Author: nian
# Blog: https://whoisnian.com
# Mail: zhuchangbao1998@gmail.com
# Created Time: 2019年05月19日 星期日 23时01分45秒
#########################################################################

# Your username and password in https://pass.neu.edu.cn
user_name="yourusername"
user_pass="password"

# Get Cookie and LoginForm
LoginForm=`curl -s -L -X GET \
    "http://ipgw.neu.edu.cn/srun_cas.php" \
    -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0' \
    -c /tmp/ipgw-cookies`

Form_action='https://pass.neu.edu.cn'`grep -oP '(?<=id="loginForm" action=")/tpass/login[^"]*' <<< $LoginForm`
Form_lt=`grep -oP '(?<=id="lt" name="lt" value=")[^"]*' <<< $LoginForm`
Form_rsa=$user_name$user_pass$Form_lt
Form_ul=${#user_name}
Form_pl=${#user_pass}
Form_execution=`grep -oP '(?<=name="execution" value=")[^"]*' <<< $LoginForm`
Form__eventId=`grep -oP '(?<=name="_eventId" value=")[^"]*' <<< $LoginForm`

# Login
LoginRes=`curl -s -k -L -X POST \
    $Form_action \
    -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0' \
    -b /tmp/ipgw-cookies \
    -d "rsa=$Form_rsa&ul=$Form_ul&pl=$Form_pl&lt=$Form_lt&execution=$Form_execution&_eventId=$Form__eventId"`

if [[ ! $LoginRes =~ "已用流量" ]]
then
    echo "Connection Failed!"
    exit
fi

# Get account information
k=$RANDOM
INFO=`curl -s -L -X POST \
    "http://ipgw.neu.edu.cn/include/auth_action.php?k=$k" \
    -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0' \
    -b /tmp/ipgw-cookies \
    -d "action=get_online_info&key=$k"`

if  [ ! -n "$INFO" ] ;then
    echo "Connection Failed!"
    exit
else
    DATA=${INFO%%,*}
    DATAG=$[$DATA/(1024*1024*1024)]
    DATAM=$[$DATA%(1024*1024*1024)/(1024*1024)]
    if [ $DATAG != 0 ];
    then
        echo "已用流量：$DATAG GiB $DATAM MiB"
    else
        echo "已用流量：$DATAM MiB"
    fi
    TEMP=${INFO#*,}
    TIME=${TEMP%%,*}
    TIMEH=$[$TIME/(60*60)]
    TIMEM=$[$TIME%(60*60)/(60)]
    TIMES=$[$TIME%60]
    echo "已用时长：$TIMEH:$TIMEM:$TIMES"
    TEMP=${TEMP#*,}
    BALANCE=${TEMP%%,*}
    echo "账户余额：$BALANCE"
    IP=${INFO##*,}
    echo "IPv4地址：$IP"
fi

