#!/bin/bash
#########################################################################
# File Name: masm.sh
# Author: nian
# Blog: https://whoisnian.com
# Mail: zhuchangbao2017@gmail.com
# Created Time: 2018年03月11日 星期日 23时50分15秒
#########################################################################

# dir
dir="/home/nian/dos/"

if [ $# -ge 1 ]
then
    basename=`basename -s .asm $1`
    dosbox -c "mount C: $dir" -c 'path %path%;C:\tools\' -c 'C:' -c "masm $1,$basename.obj;" -c "link $basename.obj,$basename.exe;" -c "$basename.exe" -c "pause" -c "exit"
else
    dosbox -c "mount C: $dir" -c 'path %path%;C:\tools\' -c 'C:' -c 'cls'
fi
