#!/bin/bash
#########################################################################
# File Name: screenchange.sh
# Author: nian
# Blog: https://whoisnian.com
# Mail: zhuchangbao1998@gmail.com
# Created Time: 2017年11月03日 星期五 22时38分04秒
#########################################################################

intern="SCREEN1"
extern="SCREEN2"

if [ $# -gt 0 ]
then
    if [ $1 -eq 1 ]
    then
        xrandr --output "$intern" --off --output "$extern" --auto
    elif [ $1 -eq 2 ]
    then
        xrandr --output "$intern" --auto --output "$extern" --off
    fi
else
    xrandr --output "$intern" --auto --output "$extern" --auto --right-of "$intern"
fi
