#!/bin/bash
#########################################################################
# File Name: status.sh
# Author: nian
# Blog: https://whoisnian.com
# Mail: zhuchangbao2017@gmail.com
# Created Time: 2017年10月30日 星期一 19时29分39秒
#########################################################################

#
# hostname
#

hostname=${HOSTNAME}

#
# ip addr
#

ipv4_addr=$(curl -s ipv4.whoisnian.com)
ipv6_addr=$(curl -s ipv6.whoisnian.com)

#
# uptime
#

uptime=$(</proc/uptime)
uptime=${uptime//.*}
secs=$((${uptime}%60))
mins=$((${uptime}/60%60))
hours=$((${uptime}/3600%24))
days=$((${uptime}/86400))
uptime="${mins}m"
if [ "${hours}" -ne "0" ]; then
	uptime="${hours}h ${uptime}"
fi
if [ "${days}" -ne "0" ]; then
	uptime="${days}d ${uptime}"
fi

#
# diskusage
#

disk_info=$(df -h -x aufs -x tmpfs --total 2>/dev/null | tail -1)
disktotal=$(awk '{print $2}' <<< "${disk_info}")
diskused=$(awk '{print $3}' <<< "${disk_info}")
diskusedper=$(awk '{print $5}' <<< "${disk_info}")
diskusage="${diskused} / ${disktotal} (${diskusedper})"

#
# memory
#

mem_info=$(</proc/meminfo)
mem_info=$(echo $(echo $(mem_info=${mem_info// /}; echo ${mem_info//kB/})))
for m in $mem_info; do
	case ${m//:*} in
		"MemTotal") memused=$((memused+=${m//*:})); memtotal=${m//*:} ;;
		"ShMem") memused=$((memused+=${m//*:})) ;;
		"MemFree"|"Buffers"|"Cached"|"SReclaimable") memused=$((memused-=${m//*:})) ;;
	esac
done
memtotal=$((memtotal / 1024))
memused=$((memused / 1024))
memusedper=$((100*${memused}/${memtotal}));
memusage="${memused}MiB / ${memtotal}MiB (${memusedper}%)"

#
# cpunum
#

cpunum=$(grep -c '^processor' /proc/cpuinfo)

#
# load average
#

load_average=$(uptime | grep -Eo '\average:.*' | awk '{print $2,$3,$4}')

echo '{
    "hostname": "'$hostname'",
    "ipv4_addr": "'$ipv4_addr'",
    "ipv6_addr": "'$ipv6_addr'",
    "uptime": "'$uptime'",
    "diskusage": "'$diskusage'",
    "memusage": "'$memusage'",
    "cpunum": "'$cpunum'",
    "load_average": "'$load_average'"
}'
