#!/bin/bash
#########################################################################
# File Name: togif.sh
# Author: nian
# Blog: https://whoisnian.com
# Mail: zhuchangbao2017@gmail.com
# Created Time: 2018年09月13日 星期四 21时53分20秒
#########################################################################

palette="/tmp/palette.png"

filters="fps=30,scale=480:-1:flags=lanczos"

ffmpeg -v warning -i "$1" -vf "$filters,palettegen" -y $palette
ffmpeg -v warning -i "$1" -i "$palette" -lavfi "$filters [x]; [x][1:v] paletteuse" -y "$2"
